env:
  global:
  - HUGO_VERSION=0.41
  matrix:
    secure: iBu7ijE1X64ewHnMLG1zR/5URU3e994JUHXTsjwXP7cTVm4KuBtLvlBcte4bNqm1iRHHybAAugjaPCaabOjc+aJRdxhDahBYGFXLiMrggKtvvI09TH15yDQCDamFPS/StHIYL4DJ1LC7Yu+mF0glrNWruK82pBho3+HcRjWd/6fIRXTxniFG4WlqJ34agUEAAqkCAoXcZZptCCYtkkw8ESkPu8iMNd0KaK6AV8REKgy81Tn8DNBxpHSQbXhpX7mRzmDtauhlrKGxuGyUBb2Z9UAzYsKF4MgghERUUBYVWziwHf+ygG9CKenDjKDh1DAJ1P5uViAJPr6QY8rTg21oiLlzl+CpyjC+SZDm/qU1ZN9k8AISh932xrpOVKbZjUG+Zog+epiROjxVBFSxh8cgUkEvGvyWHOEqUDtoYBU8OgzEv34E5Jp5FMoKNRAbO9SZKadeATmb8ZKvmDzhm+FbH63otJQQGRsBA43XJNye90+DGYxnX0PfEU0YolQN7kDZELJVpgZjzHyaLIvDmKXM+wXNpdAm6xMda3DzYvCgscAp/2LKIbGPo5/q1qaADYnGZedyhX5LL73DJIK6WNoh62LPbC+8lb92CXqbmm1zbbNu+ic3LPkeDUJZlvionVaKd5J9aucwlZIOQctawu1dOc3caKt/H6VN0ClFNzZeuPg=
before_install:
- mkdir -p bin
- curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  -o bin/hugo.tar.gz
- tar xzvvf bin/hugo.tar.gz -C ./bin
script:
- "./bin/hugo"
#- cp CNAME public/
deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master