env:
  global:
  - HUGO_VERSION=0.41
  matrix:
  - secure: ber83iXEDKrY1osh7i4A/NVXbYNVw7OBhXPlWMSr4FxyJCA6LKvHL4siiNja2aRKcjl2h5uEAojDSx+jkh4NgJHdsYHmAKoTEUMbeu5o59dTYfruRu5Kqn2Vky4w4NwB0YrM/VQrq4Q/CWir9wGj9sm1N9LkjtWhA/viyWqIMK9NlpWOuGmDf9uK6VHkmJumchXeHWheNt3B2S8khp9V2uUBzDFsxhNEaUJwyunQj9ww7w6XhSV41iLymRHLsGEnm6L0mb/j04hT0Q9pMmd/vfKzyiG1niBy961UTqcehByBW2TqxXzGruTvMIii0kcCvY0qS/4gPF6qlvT8qQmvqrP2MNrKtZf4lKiSvXbHbRDBQCNlNnkCalfYUnI9PTdgQ6Io3GuHivLPrujtvEC4/umeImkuey4DOmvLFqSInt743J8WJ4BGRjg0BKXwCFKgs21P5H2bUg10VTpxug00IFmD2/80KBwSmT5HPToZGaeHwx055Ac8uctwhaJN8op7Y0P0VEy60hx1Aircyd/PlmglWRHXPZuiWZqJAik2xUu93J+m+T8RISmAj2QEYUWCsQNiULiX5X5NLiWRbnDSqSKlaqqQr5mi47O+vLIQwX+HUCaa+EcFmXxhnGgtbTp+X9bVgQ/ZKfDbQXDxPEZ7n0//XiOAqZMUv82M5Utioaw=
before_install:
- mkdir -p bin
- curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  -o bin/hugo.tar.gz
- tar xzvvf bin/hugo.tar.gz -C ./bin
script:
- "./bin/hugo"
deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
