env:
  global:
  - HUGO_VERSION=0.41
  matrix:
  - secure: iBu7ijE1X64ewHnMLG1zR/5URU3e994JUHXTsjwXP7cTVm4KuBtLvlBcte4bNqm1iRHHybAAugjaPCaabOjc+aJRdxhDahBYGFXLiMrggKtvvI09TH15yDQCDamFPS/StHIYL4DJ1LC7Yu+mF0glrNWruK82pBho3+HcRjWd/6fIRXTxniFG4WlqJ34agUEAAqkCAoXcZZptCCYtkkw8ESkPu8iMNd0KaK6AV8REKgy81Tn8DNBxpHSQbXhpX7mRzmDtauhlrKGxuGyUBb2Z9UAzYsKF4MgghERUUBYVWziwHf+ygG9CKenDjKDh1DAJ1P5uViAJPr6QY8rTg21oiLlzl+CpyjC+SZDm/qU1ZN9k8AISh932xrpOVKbZjUG+Zog+epiROjxVBFSxh8cgUkEvGvyWHOEqUDtoYBU8OgzEv34E5Jp5FMoKNRAbO9SZKadeATmb8ZKvmDzhm+FbH63otJQQGRsBA43XJNye90+DGYxnX0PfEU0YolQN7kDZELJVpgZjzHyaLIvDmKXM+wXNpdAm6xMda3DzYvCgscAp/2LKIbGPo5/q1qaADYnGZedyhX5LL73DJIK6WNoh62LPbC+8lb92CXqbmm1zbbNu+ic3LPkeDUJZlvionVaKd5J9aucwlZIOQctawu1dOc3caKt/H6VN0ClFNzZeuPg=
  - secure: ber83iXEDKrY1osh7i4A/NVXbYNVw7OBhXPlWMSr4FxyJCA6LKvHL4siiNja2aRKcjl2h5uEAojDSx+jkh4NgJHdsYHmAKoTEUMbeu5o59dTYfruRu5Kqn2Vky4w4NwB0YrM/VQrq4Q/CWir9wGj9sm1N9LkjtWhA/viyWqIMK9NlpWOuGmDf9uK6VHkmJumchXeHWheNt3B2S8khp9V2uUBzDFsxhNEaUJwyunQj9ww7w6XhSV41iLymRHLsGEnm6L0mb/j04hT0Q9pMmd/vfKzyiG1niBy961UTqcehByBW2TqxXzGruTvMIii0kcCvY0qS/4gPF6qlvT8qQmvqrP2MNrKtZf4lKiSvXbHbRDBQCNlNnkCalfYUnI9PTdgQ6Io3GuHivLPrujtvEC4/umeImkuey4DOmvLFqSInt743J8WJ4BGRjg0BKXwCFKgs21P5H2bUg10VTpxug00IFmD2/80KBwSmT5HPToZGaeHwx055Ac8uctwhaJN8op7Y0P0VEy60hx1Aircyd/PlmglWRHXPZuiWZqJAik2xUu93J+m+T8RISmAj2QEYUWCsQNiULiX5X5NLiWRbnDSqSKlaqqQr5mi47O+vLIQwX+HUCaa+EcFmXxhnGgtbTp+X9bVgQ/ZKfDbQXDxPEZ7n0//XiOAqZMUv82M5Utioaw=
before_install:
- mkdir -p bin
- curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  -o bin/hugo.tar.gz
- tar xzvvf bin/hugo.tar.gz -C ./bin
script:
- "./bin/hugo"
deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
